# Generated by Django 3.2.2 on 2021-05-12 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_auto_20210512_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('money_amt', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payapp.customer')),
                ('money_amt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payapp.amount')),
            ],
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
