# Generated by Django 3.2.2 on 2021-05-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_auto_20210512_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='money_amt',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amt',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fromPhone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='toPhone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Amount',
        ),
    ]
